from __future__ import annotations

import argparse
import csv
import json
import os
import random
from datetime import datetime
from pathlib import Path
from typing import Literal

import numpy as np
from PIL import Image
import torch
import torch.nn as nn
from torch.amp import GradScaler, autocast
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as T
import torchvision.transforms.functional as TF
import wandb

from bs3_pseudo_label_DA3_train import (
    AMP,
    GRAD_CLIP,
    IMG_SIZE,
    MODE,
    NUM_WORKERS,
    SCRATCH_ROOT,
    SEED,
    STUDENT_MODEL,
    TEACHER_MODEL,
    TrainMode,
    forward_train,
    load_model,
    scale_invariant_rmse_loss,
)


_IMAGENET_MEAN = [0.485, 0.456, 0.406]
_IMAGENET_STD = [0.229, 0.224, 0.225]
ValidView = Literal["orig", "left", "right", "up", "down"]
VALID_VIEWS = {"orig", "left", "right", "up", "down"}
NOVEL_VIEWS = {"left", "right", "up", "down"}


class AugmentedManifestDataset(Dataset):
    """RGB/depth pairs generated by the Baseline4 novel-view script."""

    def __init__(self, manifest_path: Path, img_size: int = IMG_SIZE):
        if not manifest_path.exists():
            raise FileNotFoundError(f"Augmented dataset manifest not found: {manifest_path}")
        self.manifest_path = manifest_path
        self.img_size = img_size
        self.normalize = T.Normalize(mean=_IMAGENET_MEAN, std=_IMAGENET_STD)

        rows: list[dict[str, str]] = []
        with manifest_path.open(newline="") as f:
            reader = csv.DictReader(f)
            if not reader.fieldnames:
                raise ValueError(f"Manifest has no header: {manifest_path}")
            for row in reader:
                view = row.get("view", "")
                if view not in VALID_VIEWS:
                    raise ValueError(f"Unexpected view={view!r} in {manifest_path}")
                rgb_path = Path(row["rgb_path"])
                depth_path = Path(row["depth_path"])
                if not rgb_path.exists():
                    raise FileNotFoundError(f"RGB file listed in manifest does not exist: {rgb_path}")
                if not depth_path.exists():
                    raise FileNotFoundError(f"Depth file listed in manifest does not exist: {depth_path}")

                if view == "orig":
                    if not depth_path.name.endswith("_orig_depth.npy"):
                        raise ValueError(f"Original rows must use copied teacher pseudo-depth, got: {depth_path}")
                    pseudo_source = row.get("source_pseudo_depth_path", "")
                    if pseudo_source and not Path(pseudo_source).exists():
                        raise FileNotFoundError(f"Original pseudo-depth source does not exist: {pseudo_source}")
                elif view in NOVEL_VIEWS:
                    if view not in depth_path.name:
                        raise ValueError(f"Novel row view={view!r} does not match depth path: {depth_path}")
                rows.append(row)

        if not rows:
            raise ValueError(f"Manifest contains no usable rows: {manifest_path}")
        self.rows = rows

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int):
        row = self.rows[idx]
        image = Image.open(row["rgb_path"]).convert("RGB").resize((self.img_size, self.img_size), Image.LANCZOS)
        depth = np.load(row["depth_path"]).astype(np.float32)
        depth = np.where(np.isfinite(depth) & (depth > 0), depth, 0.0).astype(np.float32)
        if depth.shape != (self.img_size, self.img_size):
            depth = np.array(Image.fromarray(depth).resize((self.img_size, self.img_size), Image.NEAREST))

        image = self.normalize(TF.to_tensor(image))
        depth_t = torch.from_numpy(depth).unsqueeze(0)
        return image, depth_t

    def stats(self) -> dict[str, object]:
        counts: dict[str, int] = {view: 0 for view in sorted(VALID_VIEWS)}
        sources = set()
        for row in self.rows:
            counts[row["view"]] += 1
            sources.add(row.get("source_train_id", ""))
        return {
            "num_rows": len(self.rows),
            "num_sources": len(sources),
            "view_counts": counts,
        }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Baseline4 ablation B: fine-tune on original + generated novel-view pseudo-depth pairs."
    )
    parser.add_argument("--manifest", type=Path, required=True, help="Baseline4 generated dataset_manifest.csv.")
    parser.add_argument("--resume", type=Path, required=True, help="Checkpoint to resume from.")
    parser.add_argument("--epochs", type=int, default=int(os.environ.get("ADAPT_EPOCHS", "1")))
    parser.add_argument("--batch-size", type=int, default=int(os.environ.get("ADAPT_BATCH", "8")))
    parser.add_argument("--lr", type=float, default=float(os.environ.get("ADAPT_LR", "1e-8")))
    parser.add_argument("--weight-decay", type=float, default=float(os.environ.get("ADAPT_WEIGHT_DECAY", "1e-4")))
    parser.add_argument("--expected-samples", type=int, default=int(os.environ.get("EXPECTED_SAMPLES", "1250")))
    parser.add_argument("--expected-sources", type=int, default=int(os.environ.get("EXPECTED_SOURCES", "250")))
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--mode", choices=["full_head", "surface_head", "lora_dpt_blocks"], default=MODE)
    parser.add_argument("--wandb-project", default=os.environ.get("WANDB_PROJECT", "monocular-depth-estimation"))
    parser.add_argument("--wandb-name", default=os.environ.get("WANDB_RUN_NAME", ""))
    return parser.parse_args()


def validate_dataset_shape(ds: AugmentedManifestDataset, expected_samples: int, expected_sources: int) -> dict[str, object]:
    stats = ds.stats()
    if expected_samples > 0 and stats["num_rows"] != expected_samples:
        raise ValueError(f"Expected {expected_samples} augmented samples, got {stats['num_rows']}")
    if expected_sources > 0 and stats["num_sources"] != expected_sources:
        raise ValueError(f"Expected {expected_sources} source images, got {stats['num_sources']}")

    view_counts = stats["view_counts"]
    if len(set(view_counts.values())) != 1:
        raise ValueError(f"Each view should appear equally often, got {view_counts}")
    return stats


def train_epoch(
    model,
    loader,
    optimizer,
    scaler,
    device: torch.device,
    epoch: int,
    mode: TrainMode,
) -> tuple[float, int]:
    model.train()
    if mode in ("full_head", "surface_head"):
        model.model.backbone.eval()

    total = 0.0
    steps = 0
    for i, (images, depths) in enumerate(loader, start=1):
        images, depths = images.to(device), depths.to(device)
        optimizer.zero_grad(set_to_none=True)
        with autocast("cuda", enabled=AMP):
            preds = forward_train(model, images)
            loss = scale_invariant_rmse_loss(preds, depths)
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
        scaler.step(optimizer)
        scaler.update()

        total += loss.item()
        steps += 1
        global_step = (epoch - 1) * len(loader) + i
        wandb.log({"train_loss_step": loss.item(), "epoch": epoch}, step=global_step)
        if i == 1 or i % 20 == 0 or i == len(loader):
            print(f"  [{i}/{len(loader)}] loss={loss.item():.4f}")

    return total / max(1, steps), steps


def save_checkpoint(
    model,
    ckpt_dir: Path,
    epoch: int,
    global_step: int,
    train_loss: float,
    args: argparse.Namespace,
    source_meta: dict,
    dataset_stats: dict[str, object],
) -> Path:
    ckpt = {
        "epoch": epoch,
        "global_step": global_step,
        "model": model.state_dict(),
        "train_loss": train_loss,
        "lr": args.lr,
        "source_checkpoint": str(args.resume),
        "source_checkpoint_epoch": source_meta.get("epoch"),
        "source_checkpoint_global_step": source_meta.get("global_step"),
        "source_checkpoint_val_si_rmse": source_meta.get("val_si_rmse"),
        "source_checkpoint_val_trigger": source_meta.get("val_trigger"),
        "augmented_manifest": str(args.manifest),
        "dataset_stats": dataset_stats,
        "train_target": "baseline4_original_plus_novel_teacher_pseudo_depth",
        "validation_target": "none",
    }
    epoch_path = ckpt_dir / f"epoch_{epoch:02d}.pth"
    torch.save(ckpt, epoch_path)
    torch.save(ckpt, ckpt_dir / "last.pth")
    return epoch_path


def main() -> None:
    args = parse_args()
    if not args.resume.exists():
        raise FileNotFoundError(f"Resume checkpoint not found: {args.resume}")

    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type != "cuda":
        print("Warning: CUDA is not available, using CPU.")

    current_datetime = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    output_dir = args.output_dir or (
        SCRATCH_ROOT / f"models/baseline4-ablationB-aug-{STUDENT_MODEL}-{args.mode}-{current_datetime}"
    )
    ckpt_dir = output_dir / "checkpoints"
    ckpt_dir.mkdir(parents=True, exist_ok=False)

    print(f"Output dir: {output_dir}")
    print(f"Resume checkpoint: {args.resume}")
    print(f"Augmented manifest: {args.manifest}")
    print(f"Epochs: {args.epochs}")
    print(f"LR: {args.lr:.2e}")

    dataset = AugmentedManifestDataset(args.manifest)
    dataset_stats = validate_dataset_shape(dataset, args.expected_samples, args.expected_sources)
    print(f"Dataset stats: {dataset_stats}")
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=True,
    )

    mode: TrainMode = args.mode  # type: ignore[assignment]
    model = load_model(device, mode=mode)
    source_ckpt = torch.load(args.resume, map_location=device)
    model.load_state_dict(source_ckpt["model"])
    source_meta = {
        "epoch": source_ckpt.get("epoch"),
        "global_step": source_ckpt.get("global_step"),
        "val_si_rmse": source_ckpt.get("val_si_rmse"),
        "val_trigger": source_ckpt.get("val_trigger"),
    }
    (output_dir / "source_checkpoint_metadata.json").write_text(json.dumps(source_meta, indent=2) + "\n")

    run_name = args.wandb_name or f"baseline4-ablationB-aug-{STUDENT_MODEL}-{mode}-{current_datetime}"
    wandb.init(
        project=args.wandb_project,
        name=run_name,
        config={
            "experiment": "baseline4_ablationB_augmented_adapt",
            "teacher_model": TEACHER_MODEL,
            "student_model": STUDENT_MODEL,
            "mode": mode,
            "img_size": IMG_SIZE,
            "train_batch": args.batch_size,
            "epochs": args.epochs,
            "lr": args.lr,
            "weight_decay": args.weight_decay,
            "grad_clip": GRAD_CLIP,
            "amp": AMP,
            "seed": SEED,
            "resume": str(args.resume),
            "source_checkpoint": source_meta,
            "augmented_manifest": str(args.manifest),
            "dataset_stats": dataset_stats,
            "validation_target": "none",
            "train_target": "baseline4_original_plus_novel_teacher_pseudo_depth",
        },
    )

    optimizer = AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )
    scaler = GradScaler("cuda", enabled=AMP)

    global_step = 0
    for epoch in range(1, args.epochs + 1):
        print(f"\nEpoch {epoch}/{args.epochs}")
        train_loss, steps = train_epoch(model, loader, optimizer, scaler, device, epoch, mode)
        global_step += steps
        epoch_path = save_checkpoint(model, ckpt_dir, epoch, global_step, train_loss, args, source_meta, dataset_stats)
        print(f"  train_loss={train_loss:.4f}  lr={args.lr:.2e}  saved={epoch_path}")
        wandb.log({"train_loss": train_loss, "lr": args.lr, "epoch": epoch}, step=global_step)

    (output_dir / "run_config.json").write_text(
        json.dumps(
            {
                "output_dir": str(output_dir),
                "manifest": str(args.manifest),
                "resume": str(args.resume),
                "epochs": args.epochs,
                "batch_size": args.batch_size,
                "lr": args.lr,
                "weight_decay": args.weight_decay,
                "student_model": STUDENT_MODEL,
                "teacher_model": TEACHER_MODEL,
                "mode": mode,
                "dataset_stats": dataset_stats,
                "final_checkpoint": str(ckpt_dir / "last.pth"),
            },
            indent=2,
        )
        + "\n"
    )
    wandb.finish()
    print(f"\nDone. Final checkpoint: {ckpt_dir / 'last.pth'}")


if __name__ == "__main__":
    main()
